config/routes.rb
Rails.application.routes.draw do
  # Routen für Benutzerverwaltung
  resources :users, only: [:new, :index, :edit, :update, :destroy]
  devise_for :users

  # Startseite
  root 'posts#index'

  # Post-Ressourcen
  resources :posts do
    collection do
      get :unapproved       # Für ungeprüfte Beiträge
    end
    member do
      patch :approve        # Genehmigen eines Beitrags
      delete :reject        # Ablehnen eines Beitrags
    end

    # Verschachtelte Ressourcen für Kommentare
    resources :comments, only: [:create, :destroy, :update, :edit]
  end

  # Abmeldung über devise
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'admin'
      can :manage, User
      can :manage, :all
    elsif user.role == 'lesen'
      can :read, Post
    elsif user.role == 'author'
      can [:read, :create, :update], Post
    else
      can :read, Post
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: { maximum: 500 }
  validates :user, presence: true
end

app/models/nutritional_info.rb
class NutritionalInfo < ApplicationRecord
  belongs_to :post

  # Validierungen für Nährwertfelder
  validates :calories, presence: true
  validates :sugar, presence: true
  validates :protein, presence: true
  validates :fat, presence: true
  validates :carbohydrates, presence: true

  def calculate_sugar
    sugar * 0.2
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :nutritional_info, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :nutritional_info

  # Validierungen
  validates :title, presence: true
  validates :description, presence: true
  validates :basic_knowledge, presence: true
  validates :image, presence: true
  validates :link, presence: true
  validates :best_price, numericality: { allow_nil: true }
  validates :caffeine, numericality: { allow_nil: true }
  validates :rating, numericality: { in: 1..5, allow_nil: true }

  validate :image_format

  attribute :approved, :boolean, default: false

  scope :unapproved, -> { where(approved: false) }

  def calculate_caffeine_rating
    return 1 if caffeine <= 5
    return 2 if caffeine > 6 && caffeine <= 10
    return 3 if caffeine > 11 && caffeine <= 15
    return 4 if caffeine > 16 && caffeine <= 20
    return 5 if caffeine > 30
  end

  private

  def image_format
    if image.attached? && !image.content_type.in?(%('image/png'))
      errors.add(:image, 'muss ein PNG-Bild sein')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_ROLES = %w[admin lesen author].freeze

  validates :role, inclusion: { in: VALID_ROLES }
  after_initialize :set_default_role, if: :new_record?

  private

  def set_default_role
    self.role ||= 'lesen'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'Kommentar erfolgreich erstellt'
    else
      redirect_to @post, alert: 'ERROR Kommentar konnte nicht erstellt werden'
    end
  end

  def update
    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to @post, notice: 'Kommentar erfolgreich bearbeitet.' }
        format.js   # Erlaubt die Antwort mit JS
      end
    else
      respond_to do |format|
        format.html { redirect_to @post, alert: 'Error updating comment.' }
        format.js   # Auch für Fehlerfälle mit JS antworten
      end
    end
  end


  def edit
  end

  def destroy
    @comment.destroy
    redirect_to @post, notice: 'Kommentar gelöscht'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @post.build_nutritional_info
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Beitrag wurde erfolgreich erstellt.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post.build_nutritional_info unless @post.nutritional_info
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post erfolgreich aktualisiert.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  def approve
    @post = Post.find(params[:id])
    if current_user.role == 'admin' || current_user.role == 'manager'
      @post.update(approved: true)
      redirect_to unapproved_posts_path, notice: 'Beitrag wurde erfolgreich genehmigt.'
    else
      redirect_to root_path, alert: 'Zugriff verweigert.'
    end
  end

  def unapproved
    if current_user.role == 'admin' || current_user.role == 'manager'
      @posts = Post.unapproved.includes(:user)
    else
      redirect_to root_path, alert: 'Zugriff verweigert.'
    end
  end


  def reject
    @post = Post.find(params[:id])
    if current_user.role == 'admin' || current_user.role == 'manager'
      @post.destroy
      redirect_to unapproved_posts_path

    else
      redirect_to root_path, alert: 'Zugriff verweigert.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :rating, :image, :link, :best_price, :caffeine, :basic_knowledge, nutritional_info_attributes: [:calories, :sugar, :protein, :fat, :carbohydrates])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'Benutzer erfolgreich angelegt.'
    else
      render :new  #
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'Benutzer erfolgreich aktualisiert.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'Benutzer erfolgreich gelöscht.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :role) # E-Mail, Passwort und Rolle aktualisieren
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.haml
= simple_form_for [ @post, @post.comments.build ], html: { class: 'comment-form' } do |form|
  .form-group
    = form.input :content, label: 'Kommentar erstellen:', input_html: { class: 'form-input', rows: 4 }, required: false
    = form.button :submit, 'Kommentar erstellen', class: 'submit-button'

app/views/comments/edit.html.haml
%h2 Kommentar bearbeiten
= form_with(model: [@post, @comment], html: { class: 'post-form' }, local: true) do |form|
  .field
    = form.text_area :content, { class: 'form-textarea' }

  .button-container
    = form.submit "Änderungen speichern", class: 'submit-button'
    = link_to 'Abbrechen', @post, class: 'submit-button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %title Mate-Imperium
    %link{ rel: "stylesheet", href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" }
    %meta{ content: "width=device-width,initial-scale=1", name: "viewport" }/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = favicon_link_tag 'mate-icon.png', rel: 'icon', type: 'image/png'
  %body
    .topbar
      %div.logo
        %i.bi.bi-house.topbar-icon
        %span.site-title Mate-Imperium

      %div.auth-links
        = link_to 'Übersicht', posts_path, class: 'button back-button'

        - if user_signed_in?
          - if current_user.role == 'admin' || current_user.role == 'manager'
            %a.admin-button{ href: unapproved_posts_url } Genehmigen
            %a.admin-button{ href: users_url } Benutzerverwaltung
          %a.logout-button{ href: destroy_user_session_path, method: :delete, title: "Abmelden" } Abmelden
        - else
          %a.login-button{ href: new_user_session_path, title: "Anmelden" } Anmelden
          %a.register-button{ href: new_user_registration_path, title: "Registrieren" } Registrieren

    = yield

app/views/posts/_form.html.haml
= simple_form_for @post, html: { class: 'post-form' } do |form|
  - if @post.errors.any?
    #error_explanation
      %h2 Fehler
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  %h3.general-info-title Allgemein
  = form.input :title, label: 'Titel', input_html: { class: 'form-input' }

  = form.input :description, label: 'Beschreibung (Geschmackserlebnis)', input_html: { class: 'form-textarea' }, as: :text

  = form.input :basic_knowledge, label: 'Einführung und wissenwertes', input_html: { class: 'form-textarea' }, as: :text

  = form.input :image, label: 'Bild hochladen', input_html: { class: 'form-file', accept: '.png' }, as: :file

  %br
  %h3.nutritional-info-title Nährwerte (pro 100 ml)
  = form.fields_for :nutritional_info do |nutrition_form|
    = nutrition_form.input :calories, label: 'Kalorien (kcal)', input_html: { class: 'nutritional-input' }, as: :float, step: 0.01
    = nutrition_form.input :carbohydrates, label: 'Kohlenhydrate (g)', input_html: { class: 'nutritional-input' }, as: :float, step: 0.01
    = nutrition_form.input :sugar, label: 'Zucker (g)', input_html: { class: 'nutritional-input' }, as: :float, step: 0.01
    = nutrition_form.input :protein, label: 'Protein (g)', input_html: { class: 'nutritional-input' }, as: :float, step: 0.01
    = nutrition_form.input :fat, label: 'Fett (g)', input_html: { class: 'nutritional-input' }, as: :float, step: 0.01


  %br
  %h3.additional-info-title Zusätzliche Informationen
  = form.input :link, label: 'Best Preis Link', input_html: { class: 'form-input' }

  = form.input :best_price, label: 'Gefundener Bestpreis', input_html: { class: 'form-input' }, as: :float, step: 0.01

  = form.input :caffeine, label: 'Koffein (mg)', input_html: { class: 'form-input' }

  = form.input :rating, label: 'Sternebewertung', input_html: { class: 'form-input' }, as: :float, in: 1..5

  = form.button :submit, 'Beitrag erstellen', class: 'submit-button'

app/views/posts/edit.html.haml
%h1 Beitrag bearbeiten
= render 'form', submit_button_text: 'Beitrag aktualisieren'
.button-container
  = link_to 'Zurück zur Übersicht', posts_path, class: 'button back-button'

app/views/posts/index.html.haml
%div.grid
  - @posts.each do |post|
    - if post.approved?
      %div.grid-item
        %h2.post-title= link_to post.title, post
        = image_tag post.image, class: 'post-image'

- if user_signed_in?
  - if can?(:create, Post)
    = link_to 'Neuen Beitrag erstellen', new_post_path, class: 'button new-post-button'

app/views/posts/new.html.haml
%h1 Neuen Beitrag erstellen
= render 'form', submit_button_text: 'Beitrag erstellen'

app/views/posts/show.html.haml
.container-post
  .grid-container
    .image-container
      - if @post.image.attached?
        = image_tag @post.image, class: 'post-image'

    .rating-container
      %h1.post-title= @post.title
      - if !@post.approved
        %h2.status-not-approved Status: Nicht genehmigt
      %ul.rating-list
        %li
          %strong Gesamtbewertung
          %br
          - full_stars = @post.rating.to_i
          - empty_stars = 5 - full_stars
          %span
            - full_stars.times do
              %span.rating-star★
            - empty_stars.times do
              %span.rating-star☆
        %li
          %strong Koffeinbewertung
          %br
          - full_stars = @post.calculate_caffeine_rating.to_i
          - empty_stars = 5 - full_stars
          %span
            - full_stars.times do
              %span.rating-star★
            - empty_stars.times do
              %span.rating-star☆
        %li
          %strong Diabetes
          %br
          - full_stars = @post.nutritional_info.calculate_sugar.to_i
          - empty_stars = 5 - full_stars
          %span
            - full_stars.times do
              %span.rating-star★
            - empty_stars.times do
              %span.rating-star☆
        %li
          %strong Bestpreis
          %br
          = link_to "#{@post.best_price} €", @post.link

  .description-container
    %h2 Beschreibung
    %p= @post.description

  .nutritional-info-container
    %h3 Nährwerte (pro 100 ml)
    %ul.nutritional-info
      %li Kalorien: #{@post.nutritional_info.calories} kcal
      %li Kohlenhydrate: #{@post.nutritional_info.carbohydrates} g
      %li Zucker: #{@post.nutritional_info.sugar} g
      %li Protein: #{@post.nutritional_info.protein} g
      %li Fett: #{@post.nutritional_info.fat} g

  %h2 Bewertungen und Kommentare
  .review-container
    - if user_signed_in?
      = render 'comments/form'
    - @post.comments.each do |comment|
      .comment
        %div.comment-header
          - if comment.user
            %strong= comment.user.email
            - if current_user && (current_user.role == 'admin' || current_user == comment.user)
              .comment-actions
                = link_to ' ', edit_post_comment_path(@post, comment), class: 'bi bi-pencil', title: 'Bearbeiten'
                = link_to ' ', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Möchten Sie diesen Kommentar wirklich löschen?' }, class: 'bi bi-trash', title: 'Löschen'
        %p.comment-content= comment.content


  - if user_signed_in?
    %hr
    .button-container
      - if current_user.role == 'author' || current_user.role == 'admin'
        = link_to 'Bearbeiten', edit_post_url(@post), class: 'button edit-button'
      - if current_user.role == 'admin'
        = link_to 'Beitrag löschen', post_path(@post), data: { turbo_method: :delete, turbo_confirm: 'Bist du dir sicher?' }, class: 'button destroy-button'

    %hr

app/views/posts/unapproved.html.haml
%h1 Beiträge genehmigen

%table.table
  %thead
    %tr
      %th Titel
      %th Autor
      %th Aktionen
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to post.title, post, class: 'post-title'
        %td= post.user.present? ? post.user.email : 'keine E-Mail'
        %td
          .button-container
            = link_to 'Genehmigen', approve_post_path(post), method: :patch, class: 'approve-button'
            = link_to 'Ablehnen', reject_post_path(post), method: :delete, class: 'reject-button', data: { confirm: 'Sind Sie sicher, dass Sie diesen Beitrag ablehnen möchten?' }

app/views/users/edit.html.haml
%h1 Benutzer bearbeiten

= form_with(model: @user, local: true) do |form|
  .form-group
    = form.label :email
    = form.email_field :email, class: 'form-control'

  .form-group
    = form.label :password
    = form.password_field :password, class: 'form-control'

  .form-group
    = form.label :role
    = form.select :role, User::VALID_ROLES, { include_blank: true }, class: 'form-control'

  .form-group
    = form.submit 'Aktualisieren', class: 'btn btn-primary'

= link_to 'Zurück', users_path, class: 'btn btn-secondary'

app/views/users/index.html.haml
%h1 Benutzerverwaltung

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th E-Mail
      %th Rolle
      %th Aktionen
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.role
        %td
          = link_to 'Bearbeiten', edit_user_path(user), class: 'btn btn-primary'
          = link_to 'Löschen', user_path(user), method: :delete, data: { confirm: 'Bist du sicher, dass du diesen Benutzer löschen möchtest?' }, class: 'btn btn-danger'

  = link_to 'Neuen Benutzer anlegen', new_user_path, class: 'button new-post-button mb-3'

app/views/users/new.html.haml
%h1 Neuer Benutzer anlegen

= form_with(model: @user, local: true) do |form|
  .form-group
    = form.label :email
    = form.email_field :email, class: 'form-control', required: true

  .form-group
    = form.label :password
    = form.password_field :password, class: 'form-control', required: true

  .form-group
    = form.label :role
    = form.select :role, User::VALID_ROLES, { include_blank: true }, class: 'form-control', required: true

  .form-group
    = form.submit 'Benutzer anlegen', class: 'btn btn-success'

= link_to 'Zurück', users_path, class: 'btn btn-secondary mt-3'